// This file is auto-generated by @hey-api/openapi-ts

import type { FormControllerCreateV1Response, FormControllerFindAllByStatusV1Response, FormControllerFindAllV1Response, FormControllerFindOneV1Response, FormControllerUpdateV1Response, SubmissionControllerFindAllV1Response, SubmissionControllerFindOneV1Response, SubmissionControllerFindRecentV1Response, SubmissionControllerMarkAsReadV1Response, SubmissionControllerRemoveV1Response, UserControllerGetUserV1Response, UserControllerUpdateProfileV1Response } from './types.gen';

const userResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const userControllerGetUserV1ResponseTransformer = async (data: any): Promise<UserControllerGetUserV1Response> => {
    data = userResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const userControllerUpdateProfileV1ResponseTransformer = async (data: any): Promise<UserControllerUpdateProfileV1Response> => {
    data = userResponseDtoSchemaResponseTransformer(data);
    return data;
};

const formResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const formControllerFindAllV1ResponseTransformer = async (data: any): Promise<FormControllerFindAllV1Response> => {
    data = data.map((item: any) => formResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const formControllerCreateV1ResponseTransformer = async (data: any): Promise<FormControllerCreateV1Response> => {
    data = formResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const formControllerFindAllByStatusV1ResponseTransformer = async (data: any): Promise<FormControllerFindAllByStatusV1Response> => {
    data = data.map((item: any) => formResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const formControllerFindOneV1ResponseTransformer = async (data: any): Promise<FormControllerFindOneV1Response> => {
    data = formResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const formControllerUpdateV1ResponseTransformer = async (data: any): Promise<FormControllerUpdateV1Response> => {
    data = formResponseDtoSchemaResponseTransformer(data);
    return data;
};

const submissionResponseDtoSchemaResponseTransformer = (data: any) => {
    data.submittedAt = new Date(data.submittedAt);
    return data;
};

export const submissionControllerFindAllV1ResponseTransformer = async (data: any): Promise<SubmissionControllerFindAllV1Response> => {
    data = data.map((item: any) => submissionResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const submissionControllerFindRecentV1ResponseTransformer = async (data: any): Promise<SubmissionControllerFindRecentV1Response> => {
    data = data.map((item: any) => submissionResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const submissionControllerRemoveV1ResponseTransformer = async (data: any): Promise<SubmissionControllerRemoveV1Response> => {
    data = data.map((item: any) => submissionResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const submissionControllerFindOneV1ResponseTransformer = async (data: any): Promise<SubmissionControllerFindOneV1Response> => {
    data = data.map((item: any) => submissionResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const submissionControllerMarkAsReadV1ResponseTransformer = async (data: any): Promise<SubmissionControllerMarkAsReadV1Response> => {
    data = data.map((item: any) => submissionResponseDtoSchemaResponseTransformer(item));
    return data;
};
