// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9203' | (string & {});
};

export type ErrorMessageResponseDto = {
    /**
     *
     * HTTP status code to be expected and their meanings
     *
     * 200 - Request was successful
     *
     * 201 - Request was successful and a new resource was created
     *
     * 400 - Request failed due to bad request, invalid data, or request body syntax error
     *
     * 401 - Unauthorized request (Request requires authentication)
     *
     * 403 - Request was authorized but cannot be completed (e.g due to roles restrictions)
     *
     * 404 - Resource not found
     *
     * 422 - Request was received but cannot be processed
     *
     * 500 - Internal Server error
     *
     */
    statusCode: number;
    /**
     * Human readable error message
     */
    message: string | Array<string>;
    /**
     * Machine readable error message
     */
    error?: string;
};

export type SignupDto = {
    /**
     * Email of the user
     */
    email: string;
    /**
     * Password of the user
     */
    password: string;
    /**
     * Firstname of the user
     */
    firstName: string;
    /**
     * Lastname of the user
     */
    lastName: string;
};

export type LoginUserResponseDto = {
    /**
     * The id of the user
     */
    id: string;
    /**
     * The email address of the user
     */
    email: string;
};

export type LoginResponseDto = {
    user: LoginUserResponseDto;
    /**
     * The access token to send authenticated request
     */
    access_token: string;
    /**
     * A short message about your request
     */
    message: string;
};

export type LoginDto = {
    /**
     * Email of the user
     */
    email: string;
    /**
     * Password of the user
     */
    password: string;
};

export type ChangePasswordDto = {
    /**
     * Old password of the user
     */
    oldPassword: string;
    /**
     * New password of the user
     */
    newPassword: string;
};

export type GeneralOkResponseDto = {
    /**
     * Human readable message
     */
    message: string;
};

export type RequestResetPasswordLinkDto = {
    /**
     * Email of the account
     */
    email: string;
};

export type ResetPasswordDto = {
    /**
     * New password to change to
     */
    newPassword: string;
    /**
     * Token sent to the user email
     */
    token: string;
};

export type UserResponseDto = {
    /**
     * The id of the user
     */
    id: string;
    /**
     * The id of the user on polar.sh
     */
    polar_customer_id: {
        [key: string]: unknown;
    };
    /**
     * The first name of the user
     */
    firstName: string;
    /**
     * The last name of the user
     */
    lastName: string;
    /**
     * The email address of the user
     */
    email: string;
    /**
     * The creation date of the user account
     */
    createdAt: Date;
    /**
     * The last time the user account was updated
     */
    updatedAt: Date;
};

export type UpdateUserDto = {
    /**
     * The first name of the user
     */
    firstName?: string;
    /**
     * The last name of the user
     */
    lastName?: string;
};

export type StatsResponseDto = {
    /**
     * Total number of forms
     */
    totalForms: number;
    /**
     * Total number of active forms
     */
    totalActiveForms: number;
    /**
     * Total number of submissions
     */
    totalSubmissions: number;
    /**
     * Usage limit for this month
     */
    usageLimit: number;
};

export type CreateFormDto = {
    /**
     * The name to give the form
     */
    name: string;
    /**
     * An optional description for the form
     */
    description?: string;
};

export type FormCountResponse = {
    /**
     * Total number of submission
     */
    submissions: number;
};

export type FormResponseDto = {
    /**
     * Id of the from
     */
    id: string;
    /**
     * a short id for this from, used for submission
     */
    slug: string;
    /**
     * Name of the from
     */
    name: string;
    /**
     * Description of the from
     */
    description: string | null;
    /**
     * Status of the from
     */
    status: 'active' | 'paused' | 'archived';
    /**
     * The email to deliver submission notification to
     */
    targetEmail: string;
    /**
     * Email submission notification status
     */
    emailNotification: boolean;
    /**
     * Link to redirect user to after successful submission
     */
    redirectLink: string | null;
    /**
     * Id of the owner of the from
     */
    userId: string;
    /**
     * Counts of relations to form
     */
    _count: FormCountResponse;
    /**
     * Date the  from was created
     */
    createdAt: Date;
    /**
     * Last date the form was updated
     */
    updatedAt: Date;
};

export type UpdateFormDto = {
    /**
     * The name to give the form
     */
    name?: string;
    /**
     * An optional description for the form
     */
    description?: string;
    /**
     * Status of the form
     */
    status?: 'active' | 'paused' | 'archived';
    /**
     * Change target email
     */
    targetEmail?: string;
    /**
     * Enable or disable email notification
     */
    emailNotification?: boolean;
    /**
     * Change redirect URL
     */
    redirectUrl?: string;
};

export type Body = {
    [key: string]: unknown;
};

export type SubmissionFormDto = {
    /**
     * Id of the from
     */
    id: string;
    /**
     * a short id for this from, used for submission
     */
    slug: string;
    /**
     * Name of the from
     */
    name: string;
    /**
     * Description of the from
     */
    description: string | null;
    /**
     * Link to redirect user to after successful submission
     */
    redirectLink: string | null;
};

export type SubmissionResponseDto = {
    /**
     * Id of the submission
     */
    id: string;
    /**
     * Email from the submission fields, if the field "email" exists
     */
    email: string | null;
    /**
     * Country of the user that submitted the form
     */
    country: string;
    /**
     * IP address of the user that submitted the form
     */
    ipAddress: string;
    /**
     * JSON payload of the form data
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * URL where the form was submitted on, if available
     */
    referrer: string;
    /**
     * Browser user-agent of the submitter
     */
    userAgent: string;
    /**
     * If submission as been read
     */
    read: boolean;
    /**
     * Id of the form this submission is under
     */
    formId: string;
    /**
     * Id of the form this submission is under
     */
    form: SubmissionFormDto;
    /**
     * The time this submission was made
     */
    submittedAt: Date;
};

export type HealthControllerHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthControllerHealthCheckErrors = {
    /**
     * The Health Check is not successful
     */
    503: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        };
    };
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type HealthControllerHealthCheckError = HealthControllerHealthCheckErrors[keyof HealthControllerHealthCheckErrors];

export type HealthControllerHealthCheckResponses = {
    /**
     * The Health Check is successful
     */
    200: {
        status?: string;
        info?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        error?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        } | null;
        details?: {
            [key: string]: {
                status: string;
                [key: string]: unknown;
            };
        };
    };
};

export type HealthControllerHealthCheckResponse = HealthControllerHealthCheckResponses[keyof HealthControllerHealthCheckResponses];

export type AuthControllerSignupV1Data = {
    body: SignupDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/signup';
};

export type AuthControllerSignupV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type AuthControllerSignupV1Error = AuthControllerSignupV1Errors[keyof AuthControllerSignupV1Errors];

export type AuthControllerSignupV1Responses = {
    201: LoginResponseDto;
};

export type AuthControllerSignupV1Response = AuthControllerSignupV1Responses[keyof AuthControllerSignupV1Responses];

export type AuthControllerLoginV1Data = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthControllerLoginV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type AuthControllerLoginV1Error = AuthControllerLoginV1Errors[keyof AuthControllerLoginV1Errors];

export type AuthControllerLoginV1Responses = {
    200: LoginResponseDto;
};

export type AuthControllerLoginV1Response = AuthControllerLoginV1Responses[keyof AuthControllerLoginV1Responses];

export type AuthControllerChangePasswordV1Data = {
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/recovery/change-password';
};

export type AuthControllerChangePasswordV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type AuthControllerChangePasswordV1Error = AuthControllerChangePasswordV1Errors[keyof AuthControllerChangePasswordV1Errors];

export type AuthControllerChangePasswordV1Responses = {
    200: GeneralOkResponseDto;
};

export type AuthControllerChangePasswordV1Response = AuthControllerChangePasswordV1Responses[keyof AuthControllerChangePasswordV1Responses];

export type AuthControllerResetPasswordV1Data = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/recover/reset-password-link';
};

export type AuthControllerResetPasswordV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type AuthControllerResetPasswordV1Error = AuthControllerResetPasswordV1Errors[keyof AuthControllerResetPasswordV1Errors];

export type AuthControllerResetPasswordV1Responses = {
    200: GeneralOkResponseDto;
};

export type AuthControllerResetPasswordV1Response = AuthControllerResetPasswordV1Responses[keyof AuthControllerResetPasswordV1Responses];

export type AuthControllerVerifyResetPasswordLinkV1Data = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/api/v1/auth/recover/verify-reset-password-link';
};

export type AuthControllerVerifyResetPasswordLinkV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type AuthControllerVerifyResetPasswordLinkV1Error = AuthControllerVerifyResetPasswordLinkV1Errors[keyof AuthControllerVerifyResetPasswordLinkV1Errors];

export type AuthControllerVerifyResetPasswordLinkV1Responses = {
    200: GeneralOkResponseDto;
};

export type AuthControllerVerifyResetPasswordLinkV1Response = AuthControllerVerifyResetPasswordLinkV1Responses[keyof AuthControllerVerifyResetPasswordLinkV1Responses];

export type UserControllerDeleteProfileV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/me';
};

export type UserControllerDeleteProfileV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type UserControllerDeleteProfileV1Error = UserControllerDeleteProfileV1Errors[keyof UserControllerDeleteProfileV1Errors];

export type UserControllerDeleteProfileV1Responses = {
    200: GeneralOkResponseDto;
};

export type UserControllerDeleteProfileV1Response = UserControllerDeleteProfileV1Responses[keyof UserControllerDeleteProfileV1Responses];

export type UserControllerGetUserV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/me';
};

export type UserControllerGetUserV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type UserControllerGetUserV1Error = UserControllerGetUserV1Errors[keyof UserControllerGetUserV1Errors];

export type UserControllerGetUserV1Responses = {
    200: UserResponseDto;
};

export type UserControllerGetUserV1Response = UserControllerGetUserV1Responses[keyof UserControllerGetUserV1Responses];

export type UserControllerUpdateProfileV1Data = {
    body: UpdateUserDto;
    path?: never;
    query?: never;
    url: '/api/v1/user/me';
};

export type UserControllerUpdateProfileV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type UserControllerUpdateProfileV1Error = UserControllerUpdateProfileV1Errors[keyof UserControllerUpdateProfileV1Errors];

export type UserControllerUpdateProfileV1Responses = {
    200: UserResponseDto;
};

export type UserControllerUpdateProfileV1Response = UserControllerUpdateProfileV1Responses[keyof UserControllerUpdateProfileV1Responses];

export type StatsControllerGetStatsV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/stats';
};

export type StatsControllerGetStatsV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type StatsControllerGetStatsV1Error = StatsControllerGetStatsV1Errors[keyof StatsControllerGetStatsV1Errors];

export type StatsControllerGetStatsV1Responses = {
    200: StatsResponseDto;
};

export type StatsControllerGetStatsV1Response = StatsControllerGetStatsV1Responses[keyof StatsControllerGetStatsV1Responses];

export type FormControllerFindAllV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/form';
};

export type FormControllerFindAllV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type FormControllerFindAllV1Error = FormControllerFindAllV1Errors[keyof FormControllerFindAllV1Errors];

export type FormControllerFindAllV1Responses = {
    200: Array<FormResponseDto>;
};

export type FormControllerFindAllV1Response = FormControllerFindAllV1Responses[keyof FormControllerFindAllV1Responses];

export type FormControllerCreateV1Data = {
    body: CreateFormDto;
    path?: never;
    query?: never;
    url: '/api/v1/form';
};

export type FormControllerCreateV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type FormControllerCreateV1Error = FormControllerCreateV1Errors[keyof FormControllerCreateV1Errors];

export type FormControllerCreateV1Responses = {
    201: FormResponseDto;
};

export type FormControllerCreateV1Response = FormControllerCreateV1Responses[keyof FormControllerCreateV1Responses];

export type FormControllerFindAllByStatusV1Data = {
    body?: never;
    path: {
        status: 'active' | 'paused' | 'archived';
    };
    query?: never;
    url: '/api/v1/form/status/{status}';
};

export type FormControllerFindAllByStatusV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type FormControllerFindAllByStatusV1Error = FormControllerFindAllByStatusV1Errors[keyof FormControllerFindAllByStatusV1Errors];

export type FormControllerFindAllByStatusV1Responses = {
    200: Array<FormResponseDto>;
};

export type FormControllerFindAllByStatusV1Response = FormControllerFindAllByStatusV1Responses[keyof FormControllerFindAllByStatusV1Responses];

export type FormControllerRemoveV1Data = {
    body?: never;
    path: {
        idOrSlug: string;
    };
    query?: never;
    url: '/api/v1/form/{idOrSlug}';
};

export type FormControllerRemoveV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type FormControllerRemoveV1Error = FormControllerRemoveV1Errors[keyof FormControllerRemoveV1Errors];

export type FormControllerRemoveV1Responses = {
    200: GeneralOkResponseDto;
};

export type FormControllerRemoveV1Response = FormControllerRemoveV1Responses[keyof FormControllerRemoveV1Responses];

export type FormControllerFindOneV1Data = {
    body?: never;
    path: {
        idOrSlug: string;
    };
    query?: never;
    url: '/api/v1/form/{idOrSlug}';
};

export type FormControllerFindOneV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type FormControllerFindOneV1Error = FormControllerFindOneV1Errors[keyof FormControllerFindOneV1Errors];

export type FormControllerFindOneV1Responses = {
    200: FormResponseDto;
};

export type FormControllerFindOneV1Response = FormControllerFindOneV1Responses[keyof FormControllerFindOneV1Responses];

export type FormControllerUpdateV1Data = {
    body: UpdateFormDto;
    path: {
        idOrSlug: string;
    };
    query?: never;
    url: '/api/v1/form/{idOrSlug}';
};

export type FormControllerUpdateV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type FormControllerUpdateV1Error = FormControllerUpdateV1Errors[keyof FormControllerUpdateV1Errors];

export type FormControllerUpdateV1Responses = {
    200: FormResponseDto;
};

export type FormControllerUpdateV1Response = FormControllerUpdateV1Responses[keyof FormControllerUpdateV1Responses];

export type SubmissionControllerCreateV1Data = {
    body: Body;
    path: {
        formSlug: string;
    };
    query?: never;
    url: '/api/v1/submission/f/{formSlug}';
};

export type SubmissionControllerCreateV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type SubmissionControllerCreateV1Error = SubmissionControllerCreateV1Errors[keyof SubmissionControllerCreateV1Errors];

export type SubmissionControllerCreateV1Responses = {
    201: unknown;
};

export type SubmissionControllerFindAllV1Data = {
    body?: never;
    path: {
        formIdOrSlug: string;
    };
    query?: never;
    url: '/api/v1/submission/f/{formIdOrSlug}';
};

export type SubmissionControllerFindAllV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type SubmissionControllerFindAllV1Error = SubmissionControllerFindAllV1Errors[keyof SubmissionControllerFindAllV1Errors];

export type SubmissionControllerFindAllV1Responses = {
    200: Array<SubmissionResponseDto>;
};

export type SubmissionControllerFindAllV1Response = SubmissionControllerFindAllV1Responses[keyof SubmissionControllerFindAllV1Responses];

export type SubmissionControllerFindRecentV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/submission/recent';
};

export type SubmissionControllerFindRecentV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type SubmissionControllerFindRecentV1Error = SubmissionControllerFindRecentV1Errors[keyof SubmissionControllerFindRecentV1Errors];

export type SubmissionControllerFindRecentV1Responses = {
    200: Array<SubmissionResponseDto>;
};

export type SubmissionControllerFindRecentV1Response = SubmissionControllerFindRecentV1Responses[keyof SubmissionControllerFindRecentV1Responses];

export type SubmissionControllerRemoveV1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/submission/{id}';
};

export type SubmissionControllerRemoveV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type SubmissionControllerRemoveV1Error = SubmissionControllerRemoveV1Errors[keyof SubmissionControllerRemoveV1Errors];

export type SubmissionControllerRemoveV1Responses = {
    200: Array<SubmissionResponseDto>;
};

export type SubmissionControllerRemoveV1Response = SubmissionControllerRemoveV1Responses[keyof SubmissionControllerRemoveV1Responses];

export type SubmissionControllerFindOneV1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/submission/{id}';
};

export type SubmissionControllerFindOneV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type SubmissionControllerFindOneV1Error = SubmissionControllerFindOneV1Errors[keyof SubmissionControllerFindOneV1Errors];

export type SubmissionControllerFindOneV1Responses = {
    200: Array<SubmissionResponseDto>;
};

export type SubmissionControllerFindOneV1Response = SubmissionControllerFindOneV1Responses[keyof SubmissionControllerFindOneV1Responses];

export type SubmissionControllerMarkAsReadV1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/submission/{id}/read';
};

export type SubmissionControllerMarkAsReadV1Errors = {
    '4XX': ErrorMessageResponseDto;
    '5XX': ErrorMessageResponseDto;
};

export type SubmissionControllerMarkAsReadV1Error = SubmissionControllerMarkAsReadV1Errors[keyof SubmissionControllerMarkAsReadV1Errors];

export type SubmissionControllerMarkAsReadV1Responses = {
    200: Array<SubmissionResponseDto>;
};

export type SubmissionControllerMarkAsReadV1Response = SubmissionControllerMarkAsReadV1Responses[keyof SubmissionControllerMarkAsReadV1Responses];
